SERVER_KEY_NAME_PUBLIC = "server_public.key"
SERVER_KEY_NAME_PRIVATE = "server_private.key"
SERVER_CERT_NAME = "server.pem"
KEY_SIZE = 2048
PUBLIC_EXPONENT = 65537
AMOUNT_OF_DAYS = 365

# for x509
COUNTRY_NAME = "IL"
STATE = "HAIFA"
LOCAL_NAME = "HAIFA"
ORGANIZATION = "MY COMPANY"
COMMON_NAME = "LOCAL"